package szdb

// 资金流向
const (
	TABLE_SZ_HQ_SECURITYFUNDFLOW        = "SZ_HQ_SECURITYFUNDFLOW"
	TABLE_SZ_HQ_MARKETFUNDFLOW          = "SZ_HQ_MARKETFUNDFLOW"
	TABLE_SZ_HQ_MARKETFUNDFLOW_PERIOD   = "SZ_HQ_MARKETFUNDFLOW_PERIOD"
	TABLE_SZ_HQ_SECURITYFUNDFLOW_PERIOD = "SZ_HQ_SECURITYFUNDFLOW_PERIOD" // 证券周期性历史资金流向
)
